// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimetableApi.Data;

namespace TimetableApi.Migrations
{
    [DbContext(typeof(TimetableContext))]
    [Migration("20210109213846_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TimetableApi.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Grade 5"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Grade 6"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeId = 1,
                            Name = "Adriana Grimes"
                        },
                        new
                        {
                            Id = 2,
                            GradeId = 1,
                            Name = "Nolan Kuhlman"
                        },
                        new
                        {
                            Id = 3,
                            GradeId = 1,
                            Name = "Tessie Corkery"
                        },
                        new
                        {
                            Id = 4,
                            GradeId = 1,
                            Name = "Kianna O'Conner"
                        },
                        new
                        {
                            Id = 5,
                            GradeId = 1,
                            Name = "Mrs. Richard Lindgren"
                        },
                        new
                        {
                            Id = 6,
                            GradeId = 1,
                            Name = "Jayson O'Conner"
                        },
                        new
                        {
                            Id = 7,
                            GradeId = 1,
                            Name = "Kiana Zulauf"
                        },
                        new
                        {
                            Id = 8,
                            GradeId = 1,
                            Name = "Jesus Kuhn"
                        },
                        new
                        {
                            Id = 9,
                            GradeId = 1,
                            Name = "Julia Adams Jr."
                        },
                        new
                        {
                            Id = 10,
                            GradeId = 1,
                            Name = "Miller Kassulke"
                        },
                        new
                        {
                            Id = 11,
                            GradeId = 1,
                            Name = "Lewis Corkery II"
                        },
                        new
                        {
                            Id = 12,
                            GradeId = 1,
                            Name = "Yasmeen Reichert"
                        },
                        new
                        {
                            Id = 13,
                            GradeId = 1,
                            Name = "Neva Bode IV"
                        },
                        new
                        {
                            Id = 14,
                            GradeId = 1,
                            Name = "Adolf Buckridge"
                        },
                        new
                        {
                            Id = 15,
                            GradeId = 1,
                            Name = "Ruthe Prohaska"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Maths"
                        },
                        new
                        {
                            Id = 2,
                            Title = "English"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Science"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Geometry"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Biology"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Physics"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Chemistry"
                        },
                        new
                        {
                            Id = 8,
                            Title = "World Literature"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jerrod Kilback"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Scotty Jast I"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mandy Bednar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cornell Williamson"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mr. Conor Harris"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mallie Bradtke"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alberto Gerhold"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Miss Nico Pouros"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jean Mueller"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Connie Blick"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Verlie Kris"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Noe Gulgowski"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ms. Mable Sporer"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Isidro Moen DDS"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ms. Cydney Gleichner"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Millie Crooks DDS"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.TeachersSubjects", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeachersSubjects");
                });

            modelBuilder.Entity("TimetableApi.Models.Student", b =>
                {
                    b.HasOne("TimetableApi.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("TimetableApi.Models.TeachersSubjects", b =>
                {
                    b.HasOne("TimetableApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimetableApi.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
