// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimetableApi.Data;

namespace TimetableApi.Migrations
{
    [DbContext(typeof(TimetableContext))]
    partial class TimetableContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TimetableApi.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Grade 5"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Grade 6"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeId = 1,
                            Name = "Alize Schamberger"
                        },
                        new
                        {
                            Id = 2,
                            GradeId = 1,
                            Name = "Melany Greenholt"
                        },
                        new
                        {
                            Id = 3,
                            GradeId = 1,
                            Name = "Reva Powlowski"
                        },
                        new
                        {
                            Id = 4,
                            GradeId = 1,
                            Name = "Ansel Gulgowski"
                        },
                        new
                        {
                            Id = 5,
                            GradeId = 1,
                            Name = "Heaven Abbott"
                        },
                        new
                        {
                            Id = 6,
                            GradeId = 1,
                            Name = "Aglae Greenholt"
                        },
                        new
                        {
                            Id = 7,
                            GradeId = 1,
                            Name = "Pattie Harber DVM"
                        },
                        new
                        {
                            Id = 8,
                            GradeId = 1,
                            Name = "Margie Abbott"
                        },
                        new
                        {
                            Id = 9,
                            GradeId = 1,
                            Name = "Samara Feil"
                        },
                        new
                        {
                            Id = 10,
                            GradeId = 1,
                            Name = "Antonietta Rath"
                        },
                        new
                        {
                            Id = 11,
                            GradeId = 1,
                            Name = "Miss Ayden Williamson"
                        },
                        new
                        {
                            Id = 12,
                            GradeId = 1,
                            Name = "Linwood Abbott"
                        },
                        new
                        {
                            Id = 13,
                            GradeId = 1,
                            Name = "Stephanie Rowe"
                        },
                        new
                        {
                            Id = 14,
                            GradeId = 1,
                            Name = "Ms. Angela Wiza"
                        },
                        new
                        {
                            Id = 15,
                            GradeId = 1,
                            Name = "Walter Goodwin"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Maths"
                        },
                        new
                        {
                            Id = 2,
                            Title = "English"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Science"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Geometry"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Biology"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Physics"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Chemistry"
                        },
                        new
                        {
                            Id = 8,
                            Title = "World Literature"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Andrew Morissette V"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Johathan Muller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zoe D'Amore Jr."
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ima Fadel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dr. Mabel Murazik"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Elissa McLaughlin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wilfrid Cartwright"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Caleigh Shanahan"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Enoch Kuhn"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aidan Harber"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mariam Lockman"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Blair Goodwin"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Jacey Kovacek"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Idell Haag"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Curt Renner"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cale Hansen"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.TeachersSubjects", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeachersSubjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            SubjectId = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            SubjectId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            SubjectId = 2,
                            TeacherId = 4
                        },
                        new
                        {
                            SubjectId = 3,
                            TeacherId = 5
                        },
                        new
                        {
                            SubjectId = 3,
                            TeacherId = 6
                        },
                        new
                        {
                            SubjectId = 4,
                            TeacherId = 7
                        },
                        new
                        {
                            SubjectId = 4,
                            TeacherId = 8
                        },
                        new
                        {
                            SubjectId = 5,
                            TeacherId = 9
                        },
                        new
                        {
                            SubjectId = 5,
                            TeacherId = 10
                        },
                        new
                        {
                            SubjectId = 6,
                            TeacherId = 11
                        },
                        new
                        {
                            SubjectId = 6,
                            TeacherId = 12
                        },
                        new
                        {
                            SubjectId = 7,
                            TeacherId = 13
                        },
                        new
                        {
                            SubjectId = 7,
                            TeacherId = 14
                        },
                        new
                        {
                            SubjectId = 8,
                            TeacherId = 15
                        },
                        new
                        {
                            SubjectId = 8,
                            TeacherId = 16
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Student", b =>
                {
                    b.HasOne("TimetableApi.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("TimetableApi.Models.TeachersSubjects", b =>
                {
                    b.HasOne("TimetableApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimetableApi.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
