// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimetableApi.Data;
using TimetableApi.Data.Context;

namespace TimetableApi.Migrations
{
    [DbContext(typeof(TimetableContext))]
    partial class TimetableContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TimetableApi.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Grade 5"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Grade 6"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.GradesSubjects", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SubjectId", "GradeId");

                    b.HasIndex("GradeId");

                    b.ToTable("GradesSubjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 2,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 3,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 4,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 5,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 6,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 7,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 8,
                            GradeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("TimetableApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeId = 1,
                            Name = "Braeden Monahan"
                        },
                        new
                        {
                            Id = 2,
                            GradeId = 1,
                            Name = "Yasmeen Beer"
                        },
                        new
                        {
                            Id = 3,
                            GradeId = 1,
                            Name = "Jailyn Koss"
                        },
                        new
                        {
                            Id = 4,
                            GradeId = 1,
                            Name = "Mary Beahan"
                        },
                        new
                        {
                            Id = 5,
                            GradeId = 1,
                            Name = "Mr. Dillan Lubowitz"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Maths"
                        },
                        new
                        {
                            Id = 2,
                            Title = "English"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Science"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Geometry"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Biology"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Physics"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Chemistry"
                        },
                        new
                        {
                            Id = 8,
                            Title = "World Literature"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sarah Collins"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brandi Zulauf"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alexandrine Daniel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dr. Diego Toy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gabriel Blick"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sydney Rolfson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Billy Quitzon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Alva Johns"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gustave Hayes"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kurtis Schimmel"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jared Rosenbaum"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Wallace Torp"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Litzy Funk"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Adeline O'Hara DDS"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mauricio Schimmel"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Nicolas Jenkins MD"
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.TeachersSubjects", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SubjectId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeachersSubjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            TeacherId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 1,
                            TeacherId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 2,
                            TeacherId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 2,
                            TeacherId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 3,
                            TeacherId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 3,
                            TeacherId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 4,
                            TeacherId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 4,
                            TeacherId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 5,
                            TeacherId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 5,
                            TeacherId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 6,
                            TeacherId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 6,
                            TeacherId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 7,
                            TeacherId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 7,
                            TeacherId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 8,
                            TeacherId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubjectId = 8,
                            TeacherId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int?>("LeaveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("LeaveId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Timetables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndsAt = new DateTime(2021, 1, 11, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndsAt = new DateTime(2021, 1, 11, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 3,
                            EndsAt = new DateTime(2021, 1, 11, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 3,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 4,
                            EndsAt = new DateTime(2021, 1, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 5,
                            EndsAt = new DateTime(2021, 1, 11, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 5,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 6,
                            EndsAt = new DateTime(2021, 1, 11, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 7,
                            EndsAt = new DateTime(2021, 1, 11, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 7,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 8,
                            EndsAt = new DateTime(2021, 1, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 11, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 8,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 9,
                            EndsAt = new DateTime(2021, 1, 12, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 10,
                            EndsAt = new DateTime(2021, 1, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 11,
                            EndsAt = new DateTime(2021, 1, 12, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 3,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 12,
                            EndsAt = new DateTime(2021, 1, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 13,
                            EndsAt = new DateTime(2021, 1, 12, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 5,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 14,
                            EndsAt = new DateTime(2021, 1, 12, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 15,
                            EndsAt = new DateTime(2021, 1, 12, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 7,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 16,
                            EndsAt = new DateTime(2021, 1, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 12, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 8,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 17,
                            EndsAt = new DateTime(2021, 1, 13, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 18,
                            EndsAt = new DateTime(2021, 1, 13, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 19,
                            EndsAt = new DateTime(2021, 1, 13, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 3,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 20,
                            EndsAt = new DateTime(2021, 1, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 21,
                            EndsAt = new DateTime(2021, 1, 13, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 5,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 22,
                            EndsAt = new DateTime(2021, 1, 13, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 23,
                            EndsAt = new DateTime(2021, 1, 13, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 7,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 24,
                            EndsAt = new DateTime(2021, 1, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 13, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 8,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 25,
                            EndsAt = new DateTime(2021, 1, 14, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 26,
                            EndsAt = new DateTime(2021, 1, 14, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 27,
                            EndsAt = new DateTime(2021, 1, 14, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 3,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 28,
                            EndsAt = new DateTime(2021, 1, 14, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 29,
                            EndsAt = new DateTime(2021, 1, 14, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 5,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 30,
                            EndsAt = new DateTime(2021, 1, 14, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 31,
                            EndsAt = new DateTime(2021, 1, 14, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 7,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 32,
                            EndsAt = new DateTime(2021, 1, 14, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 14, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 8,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 33,
                            EndsAt = new DateTime(2021, 1, 15, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 34,
                            EndsAt = new DateTime(2021, 1, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 35,
                            EndsAt = new DateTime(2021, 1, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 3,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 36,
                            EndsAt = new DateTime(2021, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 37,
                            EndsAt = new DateTime(2021, 1, 15, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 5,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 38,
                            EndsAt = new DateTime(2021, 1, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 39,
                            EndsAt = new DateTime(2021, 1, 15, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 7,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 40,
                            EndsAt = new DateTime(2021, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeId = 1,
                            StartAt = new DateTime(2021, 1, 15, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = 8,
                            TeacherId = 9
                        });
                });

            modelBuilder.Entity("TimetableApi.Models.GradesSubjects", b =>
                {
                    b.HasOne("TimetableApi.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimetableApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TimetableApi.Models.Student", b =>
                {
                    b.HasOne("TimetableApi.Models.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("TimetableApi.Models.TeachersSubjects", b =>
                {
                    b.HasOne("TimetableApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimetableApi.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TimetableApi.Models.Timetable", b =>
                {
                    b.HasOne("TimetableApi.Models.Grade", "Grade")
                        .WithMany("Timetables")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimetableApi.Models.Leave", "Leave")
                        .WithMany()
                        .HasForeignKey("LeaveId");

                    b.HasOne("TimetableApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimetableApi.Models.Teacher", null)
                        .WithMany("Timetables")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Leave");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TimetableApi.Models.Grade", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("TimetableApi.Models.Teacher", b =>
                {
                    b.Navigation("Timetables");
                });
#pragma warning restore 612, 618
        }
    }
}
